# Week 7
weekly practice from The Math of Intelligence by Siraj Raval

In [1]:
import numpy as np

In [2]:
# Input data
input_data = np.array([[0, 0, 1],
                      [0, 1, 1],
                      [1, 0, 1],
                      [1, 1, 1]])

output_labels = np.array([[0],
                          [1],
                          [1],
                          [0]])

print (input_data)
print (output_labels)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
[[0]
 [1]
 [1]
 [0]]


In [10]:
# Sigmoid function
def activate(x, deriv=False):
    if deriv == True:
        return x*(1-x)
    return 1 / (1 + np.exp(-x))

In [12]:
# Weight values
synaptic_weight_0 = 2 * np.random.random((3, 4)) - 1
synaptic_weight_1 = 2 * np.random.random((4, 1)) - 1

print (synaptic_weight_0)
print (synaptic_weight_1)

[[ 0.82318999  0.60663747 -0.58374882  0.01221574]
 [ 0.53178562 -0.09152426  0.54774698 -0.07761618]
 [-0.77775527  0.72917137 -0.83122391 -0.51428966]]
[[ 0.54322457]
 [-0.73133007]
 [ 0.15035655]
 [ 0.2146566 ]]


In [13]:
for j in range(60000):
    # Forward propagate through layers 0, 1, 2
    layer_0 = input_data
    layer_1 = activate(np.dot(layer_0, synaptic_weight_0))
    layer_2 = activate(np.dot(layer_1, synaptic_weight_1))
    
    # Calculate error for layer 2
    layer_2_error = output_labels - layer_2
    
    # For printing some results
    if (j % 10000) == 0: 
        print ("Error: " + str(np.mean(np.abs(layer_2_error))))
    
    # Compute gradient
    layer_2_gradient = layer_2_error * activate(layer_2, deriv=True)
    
    # Calculate error for layer 1
    layer_1_error = layer_2_gradient.dot(synaptic_weight_1.T)
    
    # Compute gradient
    layer_1_gradient = layer_1_error * activate(layer_1, deriv=True)
    
    # Update the weights using the gradients
    synaptic_weight_1 += layer_1.T.dot(layer_2_gradient)
    synaptic_weight_0 += layer_0.T.dot(layer_1_gradient)

Error: 0.499706796748
Error: 0.0102590110718
Error: 0.00704077818238
Error: 0.00566997522495
Error: 0.00486779062147
Error: 0.00432670387838


In [16]:
test_1 = activate(np.dot(np.array([0, 1, 1]), synaptic_weight_0))
print (test_1)

[  9.74834127e-01   4.48690293e-02   5.20082773e-01   1.59372994e-04]


In [18]:
test_2 = (activate(np.dot(test_1, synaptic_weight_1)))
print (test_2)

[ 0.99594418]
